const fs = require('fs');

let appJs = fs.readFileSync('src/app.js', 'utf8');

// 1. Add defaultAffiliates seed data
const defaultAffiliates = [
    {
        id: "aff_default_1",
        name: "Carlos Oliveira Marketing",
        code: "CARLOS10",
        email: "carlos.oliveira@marketingdigital.com",
        phone: "(11) 98777-6655",
        document: "342.189.908-12",
        commissionRate: 3.0,
        pixKey: "carlos.oliveira@marketingdigital.com",
        bankInfo: "Banco Itaú - Ag 0451 C/C 23890-1",
        discountBenefit: "10% de desconto na hospedagem ou 1º mês grátis",
        status: "active",
        createdAt: "2026-07-15T10:00:00.000Z",
        payouts: [
            { id: "pay_1", amount: 150.00, date: "2026-07-28T14:30:00.000Z", receipt: "PIX-E3429012" }
        ]
    },
    {
        id: "aff_default_2",
        name: "Fernanda Lima Consultoria",
        code: "FERNANDA2026",
        email: "fernanda@limaconsultoria.com.br",
        phone: "(11) 97111-2233",
        document: "28.912.456/0001-99",
        commissionRate: 2.5,
        pixKey: "28.912.456/0001-99",
        bankInfo: "Banco Bradesco - Ag 1204 C/C 8901-2",
        discountBenefit: "1º mês de manutenção grátis",
        status: "active",
        createdAt: "2026-07-20T11:20:00.000Z",
        payouts: []
    }
];

// Add defaultAffiliates array definition if not present
if (!appJs.includes('const defaultAffiliates =')) {
    const defaultDocIdx = appJs.indexOf('const defaultDocuments =');
    if (defaultDocIdx !== -1) {
        const affCode = `const defaultAffiliates = ${JSON.stringify(defaultAffiliates, null, 4)};\n\n`;
        appJs = appJs.substring(0, defaultDocIdx) + affCode + appJs.substring(defaultDocIdx);
        console.log('Added defaultAffiliates to app.js');
    }
}

// 2. Add getAffiliates function
const getAffiliatesCode = `\nfunction getAffiliates() {
    const env = getEnv();
    if (!env.affiliates) env.affiliates = [...defaultAffiliates];
    return env.affiliates;
}\n`;

if (!appJs.includes('function getAffiliates()')) {
    const getDocsIdx = appJs.indexOf('function getDocuments()');
    if (getDocsIdx !== -1) {
        appJs = appJs.substring(0, getDocsIdx) + getAffiliatesCode + appJs.substring(getDocsIdx);
        console.log('Added getAffiliates function to app.js');
    }
}

// 3. Add populateAffiliateDropdowns function
const dropdownsCode = `\nfunction populateAffiliateDropdowns() {
    const affiliates = getAffiliates();
    const select = document.getElementById('contactAffiliate');
    if (!select) return;

    const currentVal = select.value;
    select.innerHTML = '<option value="">Nenhum (Venda Direta)</option>';

    affiliates.forEach(aff => {
        const opt = document.createElement('option');
        opt.value = aff.id;
        opt.innerText = \`🤝 \${aff.name} (\${aff.code} - \${aff.commissionRate}%)\`;
        select.appendChild(opt);
    });

    select.value = currentVal;
}\n`;

if (!appJs.includes('function populateAffiliateDropdowns()')) {
    const populateIdx = appJs.indexOf('function populateContactDropdowns()');
    if (populateIdx !== -1) {
        appJs = appJs.substring(0, populateIdx) + dropdownsCode + appJs.substring(populateIdx);
        console.log('Added populateAffiliateDropdowns to app.js');
    }
}

// 4. Implement renderAffiliates function and charts
const renderAffiliatesCode = `\n// ==========================================
// AFFILIATES MODULE ENGINE
// ==========================================
let affiliateSalesChartInstance = null;
let affiliateStatusChartInstance = null;
let affiliateSearchQuery = '';
let affiliateStatusFilter = 'all';

function renderAffiliates() {
    populateAffiliateDropdowns();

    const env = getEnv();
    const affiliates = getAffiliates();
    const contacts = env.contacts || [];

    // Calculations
    const totalAffiliates = affiliates.length;
    
    // Find all contacts tied to an affiliate
    const referredContacts = contacts.filter(c => c.affiliateId);
    const monthReferrals = referredContacts.length;

    // Total revenue generated by affiliates (from converted/won contacts or total contract value)
    let totalRevenueGenerated = 0;
    let totalCommissionsEarned = 0;
    let totalCommissionsPaid = 0;

    affiliates.forEach(aff => {
        const affLeads = contacts.filter(c => c.affiliateId === aff.id);
        const affRevenue = affLeads.reduce((sum, c) => sum + (Number(c.value) || 0), 0);
        const affEarned = affRevenue * (Number(aff.commissionRate) / 100);
        const affPaid = (aff.payouts || []).reduce((sum, p) => sum + (Number(p.amount) || 0), 0);

        aff._revenue = affRevenue;
        aff._earned = affEarned;
        aff._paid = affPaid;
        aff._pending = Math.max(0, affEarned - affPaid);
        aff._leadCount = affLeads.length;
        aff._wonCount = affLeads.filter(c => c.status === 'won').length;

        totalRevenueGenerated += affRevenue;
        totalCommissionsEarned += affEarned;
        totalCommissionsPaid += affPaid;
    });

    const pendingCommissions = Math.max(0, totalCommissionsEarned - totalCommissionsPaid);

    // Update KPI Ribbon
    const setEl = (id, val) => { const el = document.getElementById(id); if (el) el.innerText = val; };
    setEl('kpiTotalAffiliates', totalAffiliates);
    setEl('kpiMonthReferrals', monthReferrals);
    setEl('kpiAffiliateRevenue', formatCurrency(totalRevenueGenerated));
    setEl('kpiPendingCommissions', formatCurrency(pendingCommissions));

    // Render Charts
    renderAffiliateCharts(affiliates, totalCommissionsPaid, pendingCommissions);

    // Render Table
    const tbody = document.getElementById('affiliatesTableBody');
    if (!tbody) return;
    tbody.innerHTML = '';

    let filtered = [...affiliates];

    if (affiliateStatusFilter === 'active') {
        filtered = filtered.filter(a => a.status === 'active');
    } else if (affiliateStatusFilter === 'pending') {
        filtered = filtered.filter(a => a._pending > 0);
    } else if (affiliateStatusFilter === 'paid') {
        filtered = filtered.filter(a => a._pending === 0 && a._paid > 0);
    }

    if (affiliateSearchQuery) {
        const q = affiliateSearchQuery.toLowerCase();
        filtered = filtered.filter(a => 
            (a.name || '').toLowerCase().includes(q) ||
            (a.code || '').toLowerCase().includes(q) ||
            (a.document || '').toLowerCase().includes(q) ||
            (a.pixKey || '').toLowerCase().includes(q)
        );
    }

    if (filtered.length === 0) {
        tbody.innerHTML = \`<tr><td colspan="8" style="text-align:center; padding: 30px; color: var(--text-muted);">Nenhum afiliado encontrado.</td></tr>\`;
        return;
    }

    filtered.forEach(aff => {
        const tr = document.createElement('tr');
        tr.style.cssText = "height: 52px; border-bottom: 1px solid var(--border-color);";
        tr.innerHTML = \`
            <td>
                <div style="display:flex; align-items:center; gap:10px;">
                    <div class="contact-avatar" style="width:34px; height:34px; font-size:11px; flex-shrink:0; background:linear-gradient(135deg, #4F46E5, #06B6D4); color:#fff; font-weight:700;">\${getInitials(aff.name)}</div>
                    <div style="min-width:0; flex:1;">
                        <span style="font-weight:700; font-size:13px; color:var(--text-primary); display:block; white-space:nowrap; overflow:hidden; text-overflow:ellipsis;" title="\${aff.name}">\${aff.name}</span>
                        <span style="font-size:11px; color:var(--text-muted);">\${aff.email} • \${aff.phone}</span>
                    </div>
                </div>
            </td>
            <td>
                <div style="display:flex; flex-direction:column; gap:2px;">
                    <span style="font-size:12px; font-weight:600; color:var(--text-primary);">\${aff.document}</span>
                    <span style="font-size:10.5px; color:var(--color-primary); font-family:monospace;" title="Chave Pix">🔑 \${aff.pixKey}</span>
                </div>
            </td>
            <td>
                <span style="display:inline-flex; align-items:center; gap:4px; font-family:monospace; font-size:12px; font-weight:700; background:rgba(79,70,229,0.1); color:#4F46E5; padding:3px 8px; border-radius:5px; border:1px solid rgba(79,70,229,0.2);">
                    🏷️ \${aff.code}
                </span>
            </td>
            <td style="text-align:center;">
                <span style="font-size:12.5px; font-weight:700; color:#06B6D4;">\${aff.commissionRate}%</span>
            </td>
            <td style="text-align:center;">
                <div style="display:flex; flex-direction:column; align-items:center;">
                    <span style="font-size:12.5px; font-weight:700; color:var(--text-primary);">\${aff._leadCount} leads</span>
                    <span style="font-size:10px; color:#059669; font-weight:600;">\${aff._wonCount} fechados</span>
                </div>
            </td>
            <td>
                <strong style="font-size:13px; color:#059669;">\${formatCurrency(aff._revenue)}</strong>
            </td>
            <td>
                <div style="display:flex; flex-direction:column;">
                    <span style="font-size:13px; font-weight:700; color:var(--text-primary);">\${formatCurrency(aff._earned)}</span>
                    <span style="font-size:10.5px; color:\${aff._pending > 0 ? '#d97706' : '#059669'}; font-weight:600;">
                        \${aff._pending > 0 ? \`⏳ \${formatCurrency(aff._pending)} pendente\` : \`✅ Pago (\${formatCurrency(aff._paid)})\`}
                    </span>
                </div>
            </td>
            <td style="text-align:right;">
                <div style="display:inline-flex; gap:4px;">
                    <button class="btn-icon-only btn-payout-aff" data-id="\${aff.id}" title="Lançar Pagamento Pix" style="color:#059669; background:rgba(5,150,105,0.1); border-radius:4px;"><i data-lucide="dollar-sign" style="width:14px;height:14px;"></i></button>
                    <button class="btn-icon-only btn-edit-aff" data-id="\${aff.id}" title="Editar Afiliado"><i data-lucide="pencil" style="width:14px;height:14px;"></i></button>
                    <button class="btn-icon-only btn-delete-aff" data-id="\${aff.id}" title="Excluir Afiliado" style="color:var(--color-danger);"><i data-lucide="trash-2" style="width:14px;height:14px;"></i></button>
                </div>
            </td>
        \`;

        tr.querySelector('.btn-payout-aff').onclick = () => openAffiliatePayoutModal(aff.id);
        tr.querySelector('.btn-edit-aff').onclick = () => openAffiliateModal(aff.id);
        tr.querySelector('.btn-delete-aff').onclick = () => deleteAffiliate(aff.id);

        tbody.appendChild(tr);
    });

    safeCreateIcons();
}

function renderAffiliateCharts(affiliates, totalPaid, totalPending) {
    if (typeof Chart === 'undefined') return;

    // 1. Sales Bar Chart
    const ctxSales = document.getElementById('affiliateSalesChart');
    if (ctxSales) {
        if (affiliateSalesChartInstance) affiliateSalesChartInstance.destroy();
        
        const topAffiliates = [...affiliates].sort((a, b) => b._revenue - a._revenue).slice(0, 6);
        const labels = topAffiliates.map(a => a.name.split(' ')[0] + ' (' + a.code + ')');
        const dataValues = topAffiliates.map(a => a._revenue);

        affiliateSalesChartInstance = new Chart(ctxSales, {
            type: 'bar',
            data: {
                labels: labels.length > 0 ? labels : ['Sem dados'],
                datasets: [{
                    label: 'Faturamento Gerado (R$)',
                    data: dataValues.length > 0 ? dataValues : [0],
                    backgroundColor: 'rgba(79, 70, 229, 0.75)',
                    borderColor: '#4F46E5',
                    borderWidth: 1,
                    borderRadius: 6
                }]
            },
            options: {
                responsive: true,
                maintainAspectRatio: false,
                plugins: { legend: { display: false } },
                scales: {
                    y: { beginAtZero: true, ticks: { callback: (v) => formatCurrency(v) } }
                }
            }
        });
    }

    // 2. Status Doughnut Chart
    const ctxStatus = document.getElementById('affiliateStatusChart');
    if (ctxStatus) {
        if (affiliateStatusChartInstance) affiliateStatusChartInstance.destroy();

        affiliateStatusChartInstance = new Chart(ctxStatus, {
            type: 'doughnut',
            data: {
                labels: ['Comissões Pagas', 'Comissões Pendentes'],
                datasets: [{
                    data: [totalPaid, totalPending],
                    backgroundColor: ['#059669', '#d97706'],
                    borderWidth: 2
                }]
            },
            options: {
                responsive: true,
                maintainAspectRatio: false,
                plugins: { legend: { position: 'bottom' } }
            }
        });
    }
}

function openAffiliateModal(id = null) {
    const affiliates = getAffiliates();
    const aff = id ? affiliates.find(a => a.id === id) : null;

    document.getElementById('affiliateFormId').value = aff ? aff.id : '';
    document.getElementById('affiliateName').value = aff ? aff.name : '';
    document.getElementById('affiliateCode').value = aff ? aff.code : '';
    document.getElementById('affiliateEmail').value = aff ? aff.email : '';
    document.getElementById('affiliatePhone').value = aff ? aff.phone : '';
    document.getElementById('affiliateDocument').value = aff ? aff.document : '';
    document.getElementById('affiliateCommissionRate').value = aff ? aff.commissionRate : '3';
    document.getElementById('affiliatePixKey').value = aff ? aff.pixKey : '';
    document.getElementById('affiliateBankInfo').value = aff ? (aff.bankInfo || '') : '';
    document.getElementById('affiliateDiscountBenefit').value = aff ? (aff.discountBenefit || '') : '10% de desconto na hospedagem ou 1º mês grátis';
    
    document.getElementById('affiliateModalTitle').innerText = aff ? 'Editar Afiliado' : 'Novo Afiliado';

    const close = () => document.getElementById('affiliateModal').classList.remove('active');
    document.getElementById('btnCloseAffiliateModal').onclick = close;
    document.getElementById('btnCancelAffiliateModal').onclick = close;

    document.getElementById('affiliateModal').classList.add('active');
}

function deleteAffiliate(id) {
    const env = getEnv();
    const aff = (env.affiliates || []).find(a => a.id === id);
    if (!aff) return;

    if (confirm(\`Excluir o afiliado "\${aff.name}" (\${aff.code})?\`)) {
        env.affiliates = env.affiliates.filter(a => a.id !== id);
        
        // Remove referral link from contacts tied to this affiliate
        (env.contacts || []).forEach(c => {
            if (c.affiliateId === id) delete c.affiliateId;
        });

        saveState();
        renderAffiliates();
        showToast('Afiliado removido com sucesso!', 'info');
    }
}

function openAffiliatePayoutModal(id) {
    const affiliates = getAffiliates();
    const aff = affiliates.find(a => a.id === id);
    if (!aff) return;

    document.getElementById('payoutAffiliateId').value = aff.id;
    document.getElementById('payoutAffiliateName').innerText = aff.name;
    document.getElementById('payoutPixKey').innerText = \`Pix: \${aff.pixKey}\`;
    document.getElementById('payoutAmount').value = aff._pending > 0 ? aff._pending.toFixed(2) : '0.00';
    document.getElementById('payoutReceipt').value = '';

    const close = () => document.getElementById('affiliatePayoutModal').classList.remove('active');
    document.getElementById('btnClosePayoutModal').onclick = close;
    document.getElementById('btnCancelPayoutModal').onclick = close;

    document.getElementById('affiliatePayoutModal').classList.add('active');
}
\n`;

if (!appJs.includes('// AFFILIATES MODULE ENGINE')) {
    appJs += renderAffiliatesCode;
    console.log('Appended AFFILIATES MODULE ENGINE to app.js');
}

// 5. Wire Form Submits and Event Listeners
const wireEventsCode = `\n// Wire Affiliate Form Submits & Toolbar Listeners
const affiliateForm = document.getElementById('affiliateForm');
if (affiliateForm) {
    affiliateForm.onsubmit = (e) => {
        e.preventDefault();
        const env = getEnv();
        if (!env.affiliates) env.affiliates = [];

        const id = document.getElementById('affiliateFormId').value;
        const name = document.getElementById('affiliateName').value.trim();
        const code = document.getElementById('affiliateCode').value.trim().toUpperCase();
        const email = document.getElementById('affiliateEmail').value.trim();
        const phone = document.getElementById('affiliatePhone').value.trim();
        const documentVal = document.getElementById('affiliateDocument').value.trim();
        const commissionRate = parseFloat(document.getElementById('affiliateCommissionRate').value) || 3.0;
        const pixKey = document.getElementById('affiliatePixKey').value.trim();
        const bankInfo = document.getElementById('affiliateBankInfo').value.trim();
        const discountBenefit = document.getElementById('affiliateDiscountBenefit').value.trim();

        if (id) {
            const existing = env.affiliates.find(a => a.id === id);
            if (existing) {
                existing.name = name;
                existing.code = code;
                existing.email = email;
                existing.phone = phone;
                existing.document = documentVal;
                existing.commissionRate = commissionRate;
                existing.pixKey = pixKey;
                existing.bankInfo = bankInfo;
                existing.discountBenefit = discountBenefit;
                showToast('Afiliado atualizado com sucesso!', 'success');
            }
        } else {
            const newAff = {
                id: 'aff_' + Date.now(),
                name,
                code,
                email,
                phone,
                document: documentVal,
                commissionRate,
                pixKey,
                bankInfo,
                discountBenefit,
                status: 'active',
                createdAt: new Date().toISOString(),
                payouts: []
            };
            env.affiliates.push(newAff);
            showToast('Novo afiliado cadastrado!', 'success');
        }

        saveState();
        document.getElementById('affiliateModal').classList.remove('active');
        renderAffiliates();
    };
}

const affiliatePayoutForm = document.getElementById('affiliatePayoutForm');
if (affiliatePayoutForm) {
    affiliatePayoutForm.onsubmit = (e) => {
        e.preventDefault();
        const env = getEnv();
        const id = document.getElementById('payoutAffiliateId').value;
        const amount = parseFloat(document.getElementById('payoutAmount').value) || 0;
        const receipt = document.getElementById('payoutReceipt').value.trim();

        const aff = (env.affiliates || []).find(a => a.id === id);
        if (aff && amount > 0) {
            if (!aff.payouts) aff.payouts = [];
            aff.payouts.push({
                id: 'pay_' + Date.now(),
                amount,
                date: new Date().toISOString(),
                receipt: receipt || 'Transferência Pix'
            });

            saveState();
            showToast(\`💰 Pagamento Pix de \${formatCurrency(amount)} registrado para \${aff.name}!\`, 'success');
            document.getElementById('affiliatePayoutModal').classList.remove('active');
            renderAffiliates();
        }
    };
}

// Wire Toolbar Listeners for Affiliates
const btnAddAffiliate = document.getElementById('btnAddAffiliate');
if (btnAddAffiliate) btnAddAffiliate.onclick = () => openAffiliateModal();

const btnOpenAffiliateLinkGenerator = document.getElementById('btnOpenAffiliateLinkGenerator');
if (btnOpenAffiliateLinkGenerator) {
    btnOpenAffiliateLinkGenerator.onclick = () => {
        const affiliates = getAffiliates();
        if (affiliates.length === 0) return showToast('Cadastre ao menos um afiliado primeiro.', 'warning');
        const code = affiliates[0].code;
        const url = \`https://webcolabs.com.br/?ref=\${code}\`;
        prompt('Link de Afiliado Gerado:', url);
    };
}

const filterAffStatus = document.getElementById('filterAffiliateStatus');
if (filterAffStatus) {
    filterAffStatus.onchange = (e) => {
        affiliateStatusFilter = e.target.value;
        renderAffiliates();
    };
}

const affSearch = document.getElementById('affiliatesSearchInput');
if (affSearch) {
    affSearch.oninput = (e) => {
        affiliateSearchQuery = e.target.value;
        renderAffiliates();
    };
}
\n`;

if (!appJs.includes('Wire Affiliate Form Submits')) {
    appJs += wireEventsCode;
    console.log('Appended Affiliate form submit & toolbar handlers to app.js');
}

// 6. Update renderAll function to include renderAffiliates and populateAffiliateDropdowns
if (appJs.includes('safeRun("renderDocuments", renderDocuments);')) {
    appJs = appJs.replace(
        'safeRun("renderDocuments", renderDocuments);',
        'safeRun("renderDocuments", renderDocuments);\n    safeRun("renderAffiliates", renderAffiliates);\n    safeRun("populateAffiliateDropdowns", populateAffiliateDropdowns);'
    );
    console.log('Added renderAffiliates to renderAll in app.js');
}

// 7. Update contactForm submit handler in app.js to save affiliateId
const oldSaveContact = `c.niche = document.getElementById("contactNiche").value;`;
const newSaveContact = `c.niche = document.getElementById("contactNiche").value;\n            c.affiliateId = document.getElementById("contactAffiliate") ? document.getElementById("contactAffiliate").value : "";`;

if (appJs.includes(oldSaveContact)) {
    appJs = appJs.replace(oldSaveContact, newSaveContact);
    console.log('Updated existing contact save handler with affiliateId');
}

const oldNewContact = `niche: document.getElementById("contactNiche").value,`;
const newNewContact = `niche: document.getElementById("contactNiche").value,\n            affiliateId: document.getElementById("contactAffiliate") ? document.getElementById("contactAffiliate").value : "",`;

if (appJs.includes(oldNewContact)) {
    appJs = appJs.replace(oldNewContact, newNewContact);
    console.log('Updated new contact save handler with affiliateId');
}

fs.writeFileSync('src/app.js', appJs, 'utf8');
console.log('Successfully updated app.js with full Affiliates module logic!');
